import { UqExt as Uq } from './JkWarehouse';
import * as SalesRegion from './SalesRegion.ui';
import * as Address from './Address.ui';
import * as Country from './Country.ui';
import * as Province from './Province.ui';
import * as City from './City.ui';
import * as County from './County.ui';
import * as Currency from './Currency.ui';
import * as Brand from './Brand.ui';
import * as ProductX from './ProductX.ui';
import * as ShippingArea from './ShippingArea.ui';
import * as Warehouse from './Warehouse.ui';
import * as WarehouseRoom from './WarehouseRoom.ui';
import * as ShelfLayer from './ShelfLayer.ui';
import * as Shelf from './Shelf.ui';
import * as ShelfBlock from './ShelfBlock.ui';
import * as StorageCondition from './StorageCondition.ui';
import * as WarehouseStorageCondition from './WarehouseStorageCondition.ui';
import * as ExpressLogistics from './ExpressLogistics.ui';
import * as OutInBoundOrder from './OutInBoundOrder.ui';
import * as OutInBoundReason from './OutInBoundReason.ui';
import * as WebUser from './WebUser.ui';
import * as StorePoint from './StorePoint.ui';
import * as Item from './Item.ui';
import * as Section from './Section.ui';
import * as OrderMain from './OrderMain.ui';
import * as Pickup from './Pickup.ui';
import * as OrderDetail from './OrderDetail.ui';
import * as WarehouseN from './WarehouseN.ui';
import * as PickupDetail from './PickupDetail.ui';
import * as ItemResearch from './ItemResearch.ui';
import * as ItemProductPack from './ItemProductPack.ui';
import * as ItemProductPackLot from './ItemProductPackLot.ui';
import * as TallyDetail from './TallyDetail.ui';
import * as TallyMain from './TallyMain.ui';
import * as Contact from './Contact.ui';
import * as DxPicking from './DxPicking.ui';
import * as OrderDetailX from './OrderDetailX.ui';
import * as DxTallyMain from './DxTallyMain.ui';
import * as WarehouseSection from './WarehouseSection.ui';
import * as ItemStore from './ItemStore.ui';
import * as IxUserWarehouse from './IxUserWarehouse.ui';
import * as IxPendingPickup from './IxPendingPickup.ui';

export function setUI(uq: Uq) {
	Object.assign(uq.SalesRegion, SalesRegion);
	Object.assign(uq.Address, Address);
	Object.assign(uq.Country, Country);
	Object.assign(uq.Province, Province);
	Object.assign(uq.City, City);
	Object.assign(uq.County, County);
	Object.assign(uq.Currency, Currency);
	Object.assign(uq.Brand, Brand);
	Object.assign(uq.ProductX, ProductX);
	Object.assign(uq.ShippingArea, ShippingArea);
	Object.assign(uq.Warehouse, Warehouse);
	Object.assign(uq.WarehouseRoom, WarehouseRoom);
	Object.assign(uq.ShelfLayer, ShelfLayer);
	Object.assign(uq.Shelf, Shelf);
	Object.assign(uq.ShelfBlock, ShelfBlock);
	Object.assign(uq.StorageCondition, StorageCondition);
	Object.assign(uq.WarehouseStorageCondition, WarehouseStorageCondition);
	Object.assign(uq.ExpressLogistics, ExpressLogistics);
	Object.assign(uq.OutInBoundOrder, OutInBoundOrder);
	Object.assign(uq.OutInBoundReason, OutInBoundReason);
	Object.assign(uq.WebUser, WebUser);
	Object.assign(uq.StorePoint, StorePoint);
	Object.assign(uq.Item, Item);
	Object.assign(uq.Section, Section);
	Object.assign(uq.OrderMain, OrderMain);
	Object.assign(uq.Pickup, Pickup);
	Object.assign(uq.OrderDetail, OrderDetail);
	Object.assign(uq.WarehouseN, WarehouseN);
	Object.assign(uq.PickupDetail, PickupDetail);
	Object.assign(uq.ItemResearch, ItemResearch);
	Object.assign(uq.ItemProductPack, ItemProductPack);
	Object.assign(uq.ItemProductPackLot, ItemProductPackLot);
	Object.assign(uq.TallyDetail, TallyDetail);
	Object.assign(uq.TallyMain, TallyMain);
	Object.assign(uq.Contact, Contact);
	Object.assign(uq.DxPicking, DxPicking);
	Object.assign(uq.OrderDetailX, OrderDetailX);
	Object.assign(uq.DxTallyMain, DxTallyMain);
	Object.assign(uq.WarehouseSection, WarehouseSection);
	Object.assign(uq.ItemStore, ItemStore);
	Object.assign(uq.IxUserWarehouse, IxUserWarehouse);
	Object.assign(uq.IxPendingPickup, IxPendingPickup);
}
export * from './JkWarehouse';
