import { UqExt as Uq, assign } from './JkDeliver';
import * as Carrier from './Carrier.ui';
import * as Customer from './Customer.ui';
import * as Address from './Address.ui';
import * as Contact from './Contact.ui';
import * as City from './City.ui';
import * as County from './County.ui';
import * as Country from './Country.ui';
import * as Brand from './Brand.ui';
import * as Province from './Province.ui';
import * as Organization from './Organization.ui';
import * as ProductX from './ProductX.ui';
import * as OrderMain from './OrderMain.ui';
import * as OrderDetail from './OrderDetail.ui';
import * as Warehouse from './Warehouse.ui';
import * as DeliverMain from './DeliverMain.ui';
import * as DeliverDetail from './DeliverDetail.ui';
import * as DeliverMainEx from './DeliverMainEx.ui';
import * as CutOffMain from './CutOffMain.ui';
import * as CutOffType from './CutOffType.ui';
import * as DeliverType from './DeliverType.ui';
import * as DxOrderDetail from './DxOrderDetail.ui';
import * as DxReturnDetail from './DxReturnDetail.ui';
import * as OrderDetailX from './OrderDetailX.ui';
import * as DxDeliverMain from './DxDeliverMain.ui';
import * as DxDeliverDetail from './DxDeliverDetail.ui';
import * as DxCutOffMain from './DxCutOffMain.ui';
import * as IxPendingDeliver from './IxPendingDeliver.ui';
import * as IxUserWarehouse from './IxUserWarehouse.ui';
import * as IxWarehouseDeliverMain from './IxWarehouseDeliverMain.ui';
import * as IxWarehouseCutOffMain from './IxWarehouseCutOffMain.ui';
import * as IxCutoffTypeDefinition from './IxCutoffTypeDefinition.ui';
	
export function setUI(uq: Uq) {
	assign(uq, 'Carrier', Carrier);
	assign(uq, 'Customer', Customer);
	assign(uq, 'Address', Address);
	assign(uq, 'Contact', Contact);
	assign(uq, 'City', City);
	assign(uq, 'County', County);
	assign(uq, 'Country', Country);
	assign(uq, 'Brand', Brand);
	assign(uq, 'Province', Province);
	assign(uq, 'Organization', Organization);
	assign(uq, 'ProductX', ProductX);
	assign(uq, 'OrderMain', OrderMain);
	assign(uq, 'OrderDetail', OrderDetail);
	assign(uq, 'Warehouse', Warehouse);
	assign(uq, 'DeliverMain', DeliverMain);
	assign(uq, 'DeliverDetail', DeliverDetail);
	assign(uq, 'DeliverMainEx', DeliverMainEx);
	assign(uq, 'CutOffMain', CutOffMain);
	assign(uq, 'CutOffType', CutOffType);
	assign(uq, 'DeliverType', DeliverType);
	assign(uq, 'DxOrderDetail', DxOrderDetail);
	assign(uq, 'DxReturnDetail', DxReturnDetail);
	assign(uq, 'OrderDetailX', OrderDetailX);
	assign(uq, 'DxDeliverMain', DxDeliverMain);
	assign(uq, 'DxDeliverDetail', DxDeliverDetail);
	assign(uq, 'DxCutOffMain', DxCutOffMain);
	assign(uq, 'IxPendingDeliver', IxPendingDeliver);
	assign(uq, 'IxUserWarehouse', IxUserWarehouse);
	assign(uq, 'IxWarehouseDeliverMain', IxWarehouseDeliverMain);
	assign(uq, 'IxWarehouseCutOffMain', IxWarehouseCutOffMain);
	assign(uq, 'IxCutoffTypeDefinition', IxCutoffTypeDefinition);
}
export * from './JkDeliver';
